version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:50000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
    volumes:
      - "/usercode/:/app"

  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
